#INSERT INTO PUBLISHER
INSERT INTO Publisher VALUES ("LSC Communications");
INSERT INTO Publisher VALUES ("12th Media Services");
INSERT INTO Publisher VALUES ("Ballantine Books");
INSERT INTO Publisher VALUES ("Bantam");
INSERT INTO Publisher VALUES ("Bantam Spectra Books");
INSERT INTO Publisher VALUES ("Cambridge University Press");
INSERT INTO Publisher VALUES ("Coventry House Publishing");
INSERT INTO Publisher VALUES ("Dutton");
INSERT INTO Publisher VALUES ("Ecco");
INSERT INTO Publisher VALUES ("Grove Press");
INSERT INTO Publisher VALUES ("Hackett Publishing Company, Inc.");
INSERT INTO Publisher VALUES ("Harper Collins");
INSERT INTO Publisher VALUES ("Harper Perennial");
INSERT INTO Publisher VALUES ("Harper Perennial Modern Classics");
INSERT INTO Publisher VALUES ("Independently published");
INSERT INTO Publisher VALUES ("Intra S.r.l.s.");
INSERT INTO Publisher VALUES ("Oxford University Press");
INSERT INTO Publisher VALUES ("Papercutz");
INSERT INTO Publisher VALUES ("Penguin");
INSERT INTO Publisher VALUES ("Penguin Books");
INSERT INTO Publisher VALUES ("Penguin Classics");
INSERT INTO Publisher VALUES ("Princeton University Press");
INSERT INTO Publisher VALUES ("Reader's Library Classics");
INSERT INTO Publisher VALUES ("ROBERT LAFFONT");
INSERT INTO Publisher VALUES ("Royal Classics");
INSERT INTO Publisher VALUES ("Scribner");
INSERT INTO Publisher VALUES ("SeaWolf Press");
INSERT INTO Publisher VALUES ("Signet");
INSERT INTO Publisher VALUES ("Simon & Schuster");
INSERT INTO Publisher VALUES ("St Martins Pr");
INSERT INTO Publisher VALUES ("University of California Press");
INSERT INTO Publisher VALUES ("University of Chicago Press");
INSERT INTO Publisher VALUES ("Vintage");
INSERT INTO Publisher VALUES ("Vintage Espanol");
INSERT INTO Publisher VALUES ("Wisehouse Classics");
