#INSERTING AUTHOR INTO BOOK 

INSERT INTO BookHasAuthor VALUES ("George Orwell","A01");
INSERT INTO BookHasAuthor VALUES ("Gabriel Garcia Marquez","A02");
INSERT INTO BookHasAuthor VALUES ("Aldous Huxley","A03");
INSERT INTO BookHasAuthor VALUES ("Fyodor Dostoevsky","A04");
INSERT INTO BookHasAuthor VALUES ("C.S. Lewis","A05");
INSERT INTO BookHasAuthor VALUES ("Mary Shelley","A06");
INSERT INTO BookHasAuthor VALUES ("John Steinbeck","A07");
INSERT INTO BookHasAuthor VALUES ("Mark Twain","A08");
INSERT INTO BookHasAuthor VALUES ("Charles Dickens","A09");
INSERT INTO BookHasAuthor VALUES ("Joseph Heller","A10");
INSERT INTO BookHasAuthor VALUES ("Homer","A11");
INSERT INTO BookHasAuthor VALUES ("Victor Hugo","A12");
INSERT INTO BookHasAuthor VALUES ("James Joyce","A13");
INSERT INTO BookHasAuthor VALUES ("Vladimir Nabokov","A14");
INSERT INTO BookHasAuthor VALUES ("Ayn Rand","A15");
INSERT INTO BookHasAuthor VALUES ("Patrick Suskind","A16");
INSERT INTO BookHasAuthor VALUES ("Franz Kafka","A17");
INSERT INTO BookHasAuthor VALUES ("Bret Easton Ellis","A18");
INSERT INTO BookHasAuthor VALUES ("Rene Goscinny","A19");
INSERT INTO BookHasAuthor VALUES ("Ray Bradbury","A20");
INSERT INTO BookHasAuthor VALUES ("Isaac Asimov","A21");
INSERT INTO BookHasAuthor VALUES ("Karl Marx","A22");
INSERT INTO BookHasAuthor VALUES ("Thomas Paine","A23");
INSERT INTO BookHasAuthor VALUES ("Niccolo Machiavelli","A24");
INSERT INTO BookHasAuthor VALUES ("Adam Smith","A25");
INSERT INTO BookHasAuthor VALUES ("Miguel de Cervantes Saavedra","A26");
INSERT INTO BookHasAuthor VALUES ("Simone de Beauvoir","A27");
INSERT INTO BookHasAuthor VALUES ("Immanuel Kant","A28");
INSERT INTO BookHasAuthor VALUES ("Charles Darwin","A29");
INSERT INTO BookHasAuthor VALUES ("Isaac Newton","A30");
INSERT INTO BookHasAuthor VALUES ("Milan Kundera","A31");
INSERT INTO BookHasAuthor VALUES ("Sun Tzu","A32");
INSERT INTO BookHasAuthor VALUES ("Jorge Luis Borges","A33");
INSERT INTO BookHasAuthor VALUES ("Gabriel Garcia Marquez","A34");
INSERT INTO BookHasAuthor VALUES ("Juan Rulfo","A35");
INSERT INTO BookHasAuthor VALUES ("Octavio Paz","A36");
INSERT INTO BookHasAuthor VALUES ("Pablo Neruda","A37");
INSERT INTO BookHasAuthor VALUES ("Richard Feynman","A38");
INSERT INTO BookHasAuthor VALUES ("Stephen Hawking","A39");
INSERT INTO BookHasAuthor VALUES ("Carl Sagan","A40");
INSERT INTO BookHasAuthor VALUES ("Silvanus P. Thompson","A41");
INSERT INTO BookHasAuthor VALUES ("Enrico Fermi","A42");
INSERT INTO BookHasAuthor VALUES ("Alexander Hamilton","A43");
INSERT INTO BookHasAuthor VALUES ("John Lcke","A44");
INSERT INTO BookHasAuthor VALUES ("Karl Popper","A45");
INSERT INTO BookHasAuthor VALUES ("Howard Zinn","A46");
INSERT INTO BookHasAuthor VALUES ("William Golding","A47");
INSERT INTO BookHasAuthor VALUES ("George Orwell","A48");
INSERT INTO BookHasAuthor VALUES ("Ernest Hemingway","A49");
INSERT INTO BookHasAuthor VALUES ("Luo Guanzhong","A50");