#INSERT AUTHOR

INSERT INTO Author VALUES ("Adam Smith");
INSERT INTO Author VALUES ("Albert Uderzo");
INSERT INTO Author VALUES ("Aldous Huxley");
INSERT INTO Author VALUES ("Alexander Hamilton");
INSERT INTO Author VALUES ("Ayn Rand");
INSERT INTO Author VALUES ("Bret Easton Ellis");
INSERT INTO Author VALUES ("C.S. Lewis");
INSERT INTO Author VALUES ("C. B. Macpherson");
INSERT INTO Author VALUES ("Carl Sagan");
INSERT INTO Author VALUES ("Charles Darwin");
INSERT INTO Author VALUES ("Charles Dickens");
INSERT INTO Author VALUES ("Enrico Fermi");
INSERT INTO Author VALUES ("Ernest Hemingway");
INSERT INTO Author VALUES ("Franz Kafka");
INSERT INTO Author VALUES ("Friedrich Engels");
INSERT INTO Author VALUES ("Fyodor Dostoevsky");
INSERT INTO Author VALUES ("Gabriel Garcia Marquez");
INSERT INTO Author VALUES ("George Orwell");
INSERT INTO Author VALUES ("Homer");
INSERT INTO Author VALUES ("Howard Zinn");
INSERT INTO Author VALUES ("Immanuel Kant");
INSERT INTO Author VALUES ("Isaac Asimov");
INSERT INTO Author VALUES ("Isaac Newton");
INSERT INTO Author VALUES ("James Joyce");
INSERT INTO Author VALUES ("James Madison");
INSERT INTO Author VALUES ("John Lcke");
INSERT INTO Author VALUES ("John Steinbeck");
INSERT INTO Author VALUES ("John Jay");
INSERT INTO Author VALUES ("Jorge Luis Borges");
INSERT INTO Author VALUES ("Joseph Heller");
INSERT INTO Author VALUES ("Juan Rulfo");
INSERT INTO Author VALUES ("Karl Marx");
INSERT INTO Author VALUES ("Karl Popper");
INSERT INTO Author VALUES ("Luo Guanzhong");
INSERT INTO Author VALUES ("Mark Twain");
INSERT INTO Author VALUES ("Martin Gardner");
INSERT INTO Author VALUES ("Mary Shelley");
INSERT INTO Author VALUES ("Miguel de Cervantes Saavedra");
INSERT INTO Author VALUES ("Milan Kundera");
INSERT INTO Author VALUES ("Niccolo Machiavelli");
INSERT INTO Author VALUES ("Octavio Paz");
INSERT INTO Author VALUES ("Pablo Neruda");
INSERT INTO Author VALUES ("Patrick Suskind");
INSERT INTO Author VALUES ("Ray Bradbury");
INSERT INTO Author VALUES ("Rene Goscinny");
INSERT INTO Author VALUES ("Richard Feynman");
INSERT INTO Author VALUES ("Silvanus P. Thompson");
INSERT INTO Author VALUES ("Simone de Beauvoir");
INSERT INTO Author VALUES ("Stephen Hawking");
INSERT INTO Author VALUES ("Sun Tzu");
INSERT INTO Author VALUES ("Thomas Paine");
INSERT INTO Author VALUES ("Victor Hugo");
INSERT INTO Author VALUES ("Vladimir Nabokov");
INSERT INTO Author VALUES ("William Golding");
